<a href="https://colab.research.google.com/github/abhaysrivastav/Pytorch/blob/master/Linear_Regression_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
from torch.nn import Linear


In [2]:
torch.manual_seed(1)
model =  Linear(in_features=1 , out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [4]:
x = torch.tensor([[2.0], [3.0]])
print(model(x))

tensor([[0.5891],
        [1.1044]], grad_fn=<AddmmBackward>)


**Custom Linear Models**

---



---



In [0]:
import torch.nn as nn


In [0]:
class LR(nn.Module):
  def __init__(self, input_size, output_size):
    super().__init__()
    self.linear = nn.Linear(input_size, output_size)
  def forward(self, x):
    pred =  self.linear(x)
    return pred 


In [28]:
torch.manual_seed(1)
model1 =  LR(1, 1)
print(list(model1.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [29]:
x = torch.tensor([[1.0], [2.0]])
print(model1.forward(x))

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)
