<a href="https://colab.research.google.com/github/abhaysrivastav/Pytorch/blob/master/Tensor_Crash_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install torch

In [0]:
import torch
import numpy as np

In [0]:
v = torch.tensor([1, 2, 3, 4, 5, 6,7])
print(v.dtype)

torch.int64


In [0]:
v[0]

tensor(1)

In [0]:
print(v[1:4])

tensor([2, 3, 4])


In [0]:
f = torch.FloatTensor([1, 2, 3, 4, 5, 6])
print(f)

tensor([1., 2., 3., 4., 5., 6.])


In [0]:
x = v.view(7,1)
x.size()

torch.Size([7, 1])

In [0]:
y = v.view(7, -1)

In [0]:
y

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]])

In [0]:
a = np.array([1 ,2 , 3, 4, 5 ])

In [0]:
a_torch = torch.from_numpy(a)
print(a_torch)
print(a_torch.dtype)

tensor([1, 2, 3, 4, 5])
torch.int64


In [0]:
a_numpy = a_torch.numpy()
print(a_numpy)


[1 2 3 4 5]


Tutorial2

In [0]:
t1 = torch.tensor([2, 4, 6])
t2 = toruc